parameters:
    zicht_solr.doctrine.subscriber.class: Zicht\Bundle\SolrBundle\Manager\Doctrine\Subscriber
services:
    zicht_solr.solr_manager:
        class: Zicht\Bundle\SolrBundle\Manager\SolrManager
        arguments:
            - @doctrine
            - @solarium.client
        calls:
            - [ setContainer, [ @service_container ] ]
    zicht_solr.solr_index_subscriber:
        class: %zicht_solr.doctrine.subscriber.class%
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_subscriber }
